### ISSUE TITLE
How to create the POST request in php

### ISSUE THREAD

**Issue by misterjoonas** [CheckoutFinland/psp-api#11]
In the legacy documentation it was described how to create the POST request in php: https://checkoutfinland.github.io/legacy-api/#payment-api-usage-example-in-php

In the new documentation the hmac calculation is described but where should the hmac value go?
Here is the listing of headers in the "The headers are:" part, but there is no hmac value listed there.
https://checkoutfinland.github.io/psp-api/#/?id=headers-and-request-signing
Is `signature` one of the headers? If so, why is it not listed in the table? I suppose `content-type` should be also listed there to make things clear.

**Comment by misterjoonas** [comment]
I have tried something like this:
```php
public function getPaymentButtons($body) {

  $url = 'https://api.checkout.fi/payments';
  $headers = [
    'checkout-account' => $this->merchantData['MERCHANT'],
    'checkout-algorithm' => self::$defaults['algorithm'],
    'checkout-method' => self::$defaults['method'],
    'checkout-nonce' => $body['reference'],
    'checkout-timestamp' => date('c'),
  ];

  // Headers must be sorted alphabetically by their key.
  ksort($headers);

  // Calculate hmac according to checkout.fi API documentation.
  $payload = $this->getHmac($body, $headers);
  $headers = [
    'content-type' => 'application/json; charset=utf-8',
    'signature' => $payload,
  ];
  $response = $this->client->request('POST', $url, [RequestOptions::HEADERS => $headers, RequestOptions::JSON => json_encode($body), RequestOptions::TIMEOUT => 20]);
}
```
But I'm getting `400 Bad request`.

**Comment by vesse** [comment]
Hi!

Please see this PR https://github.com/CheckoutFinland/psp-api/pull/10 for a PHP example.

The headers table lists the headers included in the HMAC payload, and signature header is mentioned in the paragraph above. We’ll need to see how to clarify the docs on that part.

**Comment by vesse** [comment]
The PR above was merged and now the examples tab contains a better PHP example. About your example - I don't know what the HMAC function contains but it looks to me you're sending only two headers - `content-type` and `signature`, as you overwrite the `$headers` array after the HMAC calculation by just those two.

**Comment by misterjoonas** [comment]
Nice, this was exactly what I was missing. Now I got a "Signature mismatch" response, so things are progressing.
