### ISSUE TITLE
Example for validating signature

### ISSUE THREAD

**Issue by misterjoonas** [CheckoutFinland/psp-api#12]
It's a little unclear how to validate the signature. _Merchant must check that signature is valid. Signature is calculated as described above._ But the parameters are not the same in request and response. I had to get the response query parameters, store the signature in another variable, unset the `signature` value in the parameters and then calculate the hmac value for the remaining parameters.

Here are my two functions which achieved that:
```php
/**
 * Validate return URL signature.
 */
public function validateReturnUrlSignature($query_parameters) {
  ksort($query_parameters);
  $query_signature = $query_parameters['signature'];
  unset($query_parameters['signature']);
  // Use empty body when validating response parameters.
  $calculated_mac = $this->getHmac('', $query_parameters);

  return $calculated_mac === $query_signature;
}

/**
 * Calculate hashed hmac value using body and headers.
 */
public function getHmac($body, $headers) {
  $hmac_payload = array_map(
    function ($val, $key) {
      return $key . ':' . $val;
    },
    $headers,
    array_keys($headers)
  );

  array_push($hmac_payload, $body);
  $hmac = hash_hmac(self::$defaults['algorithm'], implode("\n", $hmac_payload), $this->merchantData['SECRET_KEY']);
  return $hmac;
}
```

**Comment by vesse** [comment]
The point of having all other than `signature` query string (and header) parameters prefixed with `checkout-` is that one could easily filter them. I don't work with PHP that much but probably you can filter in PHP too.

One should be able to use exactly the same function for both request and response signature calculation if they used filter. Something like this (no real code):

```
function calculateSignature(queryStringOrHeader, body) {
  hmacPayload = queryStringOrHeader
    .keys()
    .filter((key) => key.matches('checkout-'))
    .sort()
    .map((key) => key + ':' + queryStringOrHeader[key])
    .append(body || '')
    .join('\n')

  return sha256_hmac(hmacPayload, secret)
}
```

So if you just filter all the keys that should be included you do not need to modify the query string or header parameters. When sending something, pass the return value of your HMAC function in `signature` algorithm. When verifying response signature (either from query string or headers), check that the value in `signature` matches that of the HMAC function.

**Comment by vesse** [comment]
I've updated the [PHP example](https://checkoutfinland.github.io/psp-api/#/examples?id=hmac-calculation-php) now so that it uses filtering. I'll refactor it later more to define a HMAC function that accepts values and body.

**Comment by vesse** [comment]
@misterjoonas did you get better understanding of the response HMAC verification with the updated PHP example?

Here is another example. If the query string is 

> checkout-account=375917&checkout-algorithm=sha256&checkout-amount=2964&checkout-stamp=15368167318383&checkout-reference=192387192837195&checkout-transaction-id=5d6e5950-b716-11e8-84e5-a732748dd5ab&checkout-status=ok&checkout-provider=nordea&signature=1a41292670c09e492c9c85a7dd1222cb1b8963c17bb296576e023b51b6e277fe

the signature payload would be (notice that there is a line break after `checkout-transaction-id` because of the empty body)

```
checkout-account:375917
checkout-algorithm:sha256
checkout-amount:2964
checkout-provider:nordea
checkout-reference:192387192837195
checkout-stamp:15368167318383
checkout-status:ok
checkout-transaction-id:5d6e5950-b716-11e8-84e5-a732748dd5ab

```

With node.js you could verify it easily:

```javascript
const crypto = require('crypto');
const secret = 'SAIPPUAKAUPPIAS';

const params = {
  'checkout-account': '375917',
  'checkout-algorithm': 'sha256',
  'checkout-amount': '2964',
  'checkout-stamp': '15368167318383',
  'checkout-reference': '192387192837195',
  'checkout-transaction-id': '5d6e5950-b716-11e8-84e5-a732748dd5ab',
  'checkout-status': 'ok',
  'checkout-provider': 'nordea',
  'signature': '1a41292670c09e492c9c85a7dd1222cb1b8963c17bb296576e023b51b6e277fe'
}

const payload = Object
  .keys(params)
  .sort()
  .filter((k) => /^checkout-/.test(k))
  .map((k) => [ k, params[k] ].join(':'));

// GET request has no body
payload.push('');

const calculatedHmac = crypto.createHmac('sha256', secret).update(payload.join('\n')).digest('hex');
console.log('Matches?', calculatedHmac === params.signature);
```

**Comment by misterjoonas** [comment]
Yes I'm just about to update my getHmac() function which is used for creating and validating a signature. I will post it here when I'm done with it.

**Comment by misterjoonas** [comment]
Here is the updated getHmac():
```php
/**
 * Calculate hashed hmac value using headers and optional body.
 */
public function getHmac($headers, $body = '') {
  // Filter headers to only ones starting with "checkout-" for hmac
  // calculation.
  foreach (array_keys($headers) as $key) {
    if (!preg_match('/^checkout-.*/', $key)) {
      unset($headers[$key]);
    }
  }

  // Array of key:value strings.
  $hmac_payload = array_map(
    function ($val, $key) {
      return $key . ':' . $val;
    },
    $headers,
    array_keys($headers)
  );

  array_push($hmac_payload, $body);
  $hmac = hash_hmac('sha256', implode("\n", $hmac_payload), 'SAIPPUAKAUPPIAS');
  return $hmac;
}
```
