### ISSUE TITLE
Body encoding information missing

### ISSUE THREAD

**Issue by akx** [CheckoutFinland/psp-api#2]
There's no information about the expected encoding(s) of the request bodies.
For the more seasoned reader, it's obvious that it's JSON, but it really should be explicitly stated.

I would have added this myself in #1, but there're corner cases I wasn't sure about:

* What are the accepted `Content-type`s? Does the remote end even look at `Content-type`?
* What are the accepted character encodings? Is `Content-Type: application/json;charset=PETSCII` acceptable, or is it UTF-8 always? Or must the payload perhaps always be 7-bit ASCII (i.e. with all non-7-bit-ASCII characters encoded with backslash escapes)?
* In the same encoding vein, it should probably be explicitly noted that the binary encoding of the request body, i.e. byte-by-byte what goes over the wire, should be part of the HMAC payloads? (Perhaps the HMAC examples should be moved to another page, so as to make the documentation flow a bit better?)

**Comment by mikaturunen** [comment]
* https://checkoutfinland.github.io/psp-api/#/?id=headers-and-request-signing
We have documented the character encoding and content-type.

ping @vesse and @jrasanen about the third question, anything?

**Comment by loueranta** [comment]
- Content-type has been added to the documentation
- The character encoding is now defined as UTF-8 in the documentation
- We have added some HMAC calculation examples here: https://checkoutfinland.github.io/psp-api/#/examples?id=code-examples
