### ISSUE TITLE
Add message field

### ISSUE THREAD

**Issue by jhmm** [CheckoutFinland/psp-api#21]
The old Checkout API features a field called message, that also appears in the Checkout control panel. This is somewhat useful since finding problems with payments is easier when there is ability to add custom identifying information to the payment. Using the new API, it does not seem to possible to do this.

**Comment by loueranta** [comment]
The new API has multiple fields where you can provide more details about the transaction than before. For example stamp, line item details, order id etc. 

Hope this helps.
