### ISSUE TITLE
Add an OpenAPI 3 spec?

### ISSUE THREAD

**Issue by akx** [CheckoutFinland/psp-api#3]
The API is rather _perfect_ to be described with an [OpenAPI 3](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md) document.

The current API description could then be easily autogenerated from that document instead, leading to a more "single source of truth" sort of configuration for the docs.

Having a machine-readable OpenAPI 3 spec makes it also possible to auto-generate client libraries, thus increasing adoption.

**Comment by jrasanen** [comment]
Thanks for the suggestion! We actually designed the API completely on top of OpenAPI 3, but could not find a suitable apidoc generator which allowed us to add markdown descriptions with images. So for now we only have markdown based api docs, but will publish the OpenAPI yaml. I also want to have the OpenAPI document to include proper hmac calculation.
