### ISSUE TITLE
Country parameter for List providers?

### ISSUE THREAD

**Issue by anssih** [CheckoutFinland/psp-api#30]
At least in the legacy API the customer country affected the available payment methods.

Should/could `/merchants/payment-providers` have a parameter for delivery and/or invoicing country to allow listing payment methods applicable to a specific customer country, seeing as it already has a an `amount` parameter to exclude non-applicable providers?

**Comment by vesse** [comment]
Sorry this has been left unanswered. The legacy API indeed did limit the payment methods by country but so far we've seen no such need. One can have Finnish bank account and online payment credentials even if they're not currently living in Finland or even if they were they can have their purchase delivered outside of Finland.
