### ISSUE TITLE
Migration guide?

### ISSUE THREAD

**Issue by markusve** [CheckoutFinland/psp-api#40]
Do you have any guide how to migrate from legacy API?

**Comment by loueranta** [comment]
The migration guide will be released soon. I'll get back to you when it's published.

**Comment by vesse** [comment]
@markusve initial guide now published in https://checkoutfinland.github.io/psp-api/#/migration-guide (might take a while to appear, or force refresh without cache).

All feedback is highly appreciated. I'll leave the ticket open for now should you have suggestions or comments. It is a little difficult to write a guide when there isn't really anything in common with the legacy API.

**Comment by eok8177** [comment]
Test credentials for Normal merchant account
What Test card numbers can use ? 
When I use numbers from https://docs.checkout.com/docs/testing 
I get  checkout-status=fail

On https://api.checkout.fi/payments/7665c80e-4067-11ea-8882-a731c8db3c90
get reponse
{
    "transactionId": "7665c80e-4067-11ea-8882-a731c8db3c90",
    "status": "fail",
    "amount": 1695,
    "currency": "EUR",
    "reference": "81395",
    "stamp": "1580062369",
    "createdAt": "2020-01-26T18:12:50.011Z"
}

**Comment by loueranta** [comment]
@eok8177 Sorry for the late reply, but you can find test credentials from our docs: https://checkoutfinland.github.io/psp-api/#/payment-method-providers
