### ISSUE TITLE
Payment report callbackUrl scheme is ignored

### ISSUE THREAD

**Issue by mpesari** [CheckoutFinland/psp-api#41]
https://checkoutfinland.github.io/psp-api/#/?id=payment-report-request-by-settlement-id

The `callbackUrl` is always called using insecure `http://`, regardless of actual value sent in the request (e.g. `https://example.com/report`).

I think it should require an `https` url like the other callbacks.

**Comment by vesse** [comment]
Hi,

Thanks for reporting - we'll look into this soon. I've created an issue to our internal bug tracking system, will update as soon as I have something to report.

**Comment by vesse** [comment]
@mpesari Yes there was indeed a bug. This is now fixed, and also changed to require https in callback URLs. Please verify if you have time.

**Comment by mpesari** [comment]
@vesse thanks, seems to work. Closing the issue.
