### ISSUE TITLE
Schema errors

### ISSUE THREAD

**Issue by raccna** [CheckoutFinland/psp-api#42]
Errors: 
    -attribute paths.'/settlements/{settlementId}/payments/report'. Declared path parameter settlementId needs to be defined as a path parameter in path or operation level
    -attribute paths.'/payments'(get).parameters.[created].schemas.default=`Current date` is not of type `date`
    -attribute paths.'/settlements'(get).parameters.[bankReference].maxLength is unexpected

**Comment by raccna** [comment]
Did you fix it? :D

**Comment by vesse** [comment]
@raccna yes of course, in the referenced commit https://github.com/CheckoutFinland/psp-api/commit/9858067969e5cf0d322b603f5c6030e49680daea :)
