### ISSUE TITLE
Update schema to reflect reality

### ISSUE THREAD

**Issue by mpesari** [CheckoutFinland/psp-api#57]
For example: ```PaymentRequest.customer.firstName``` has no length restrictions in the schema, but the API returns:

```json
{
  "status": "error",
  "message": "Request payload schema validation failed. Validate request against the provided schema.",
  "meta": [
    "instance.customer.firstName does not meet maximum length of 50"
  ]
}

```

Another example: ```Address.postalCode``` is not enforced by the API to match the regex ```'^\d+$'``` described in the scheme. Which behaviour is correct, restrict to the pattern or accept everything?

The schema is be useful for client/plugin-side validation, but it should be up-to-date with the validations the API actually performs.

**Comment by cibelius** [comment]
These schema restrictions should now be up to date and reflect the real API restrictions.

We apologize for taking so long to reply, we have unfortunately been neglecting the GitHub issues for the past year or so. We intend to pay more attention to our GitHub repo in the future.
