### ISSUE TITLE
Tokenized card expiration date

### ISSUE THREAD

**Issue by tssge** [CheckoutFinland/psp-api#61]
Is there a way to get the expiration date of a tokenized card in same way such as say Payment Highway API allows one to do? Or is such a feature planned?

Tokenized cards are quite hard to manage without an expiration date, as the customer cannot be reminded to add a new card to the service when his current tokenized one is about to expire. Also the API will be hammered with expired cards, as there's not way of knowing if a card is expired or not beforehand.

I hope something like PSD2 does not forbid such data to be passed outside Checkout.

It would be nice to get the last four digits of the card number as well to remind the customer which of their cards is expiring.

**Comment by tssge** [comment]
It would seem this feature is merged in 3efa8bad40d18e170cfa87d3f4a4021e2a0f80c5 (#62), however the test API does not seem to reflect the change: ```/tokenization/{checkout-tokenization-id}``` still returns only the token itself

In the documentation there is the following remark for card details: "Present if verification was successful", so do card details need some kind of additional verification to be available?

**Comment by cibelius** [comment]
Hey @tssge and thanks for your issue report!

~~This feature will be out in our next release, so Wednesday 25.3. next week.~~ *EDIT: feature released as hotfix today Mon 16.3. ~11:15 UTC+2*

We have mistakingly updated the documentation prematurely to reflect the upcoming release, even though the feature is not out yet. My bad, sorry!

The card details won't require any additional verification.

**Comment by cibelius** [comment]
Hi again @tssge,

We decided to hotfix this update straight away, and the card details should be released and available now.

Please let us know if you run into any issues with the update or the API!
