### ISSUE TITLE
Merchant Initiated Transactions (MIT) redirectUrls mandatory?

### ISSUE THREAD

**Issue by pkilpo** [CheckoutFinland/psp-api#65]
Merchant Initiated Transactions (MIT) can be used to charge with token without user beign present. Documentation says it uses same Payment payload as other payments (exept additional token field). There redirectURL is a mandatory field. However when using MIT in server to accomplish eg. recurring payments there is no webserver/browser present where redirect could be made.

**Comment by Ahtoranta** [comment]
Hi, sorry for the delay.  The urls are mandatory as the payload validation goes thru the same pipe as non-token payments. Redirect urls can be empty strings.
