### ISSUE TITLE
Testing 3dsecure with Customer Initiated Transactions

### ISSUE THREAD

**Issue by tssge** [CheckoutFinland/psp-api#66]
Is there a way to test 3dsecure with Customer Initiated Transactions (CIT) in the tokenization API?

Eg. is it possible to force return of status code 403 with the threeDSecureUrl set from the API when testing?

It might be helpful in production as well if someone were to want to 3dsecure authenticate all customer initiated payments (though I am not sure if there are some costs associated with this).

The gist https://gist.github.com/Keksike/a5941770c5da41f539788f28cdd01777 included in https://github.com/CheckoutFinland/psp-api/issues/59#issuecomment-578691867 contains the header value ```checkout-use-three-d-secure```, perhaps it is related.

**Comment by Ahtoranta** [comment]
Hi. Return values cannot forced but here are some cards that can be used for testing different scenarios. We will add these cards to our documentation also soon. 

Tokenization OK Payment OK, Successful 3D Secure. 3DS form password "secret".
- 4153013999700313	
- 11/2023	
- 313	

Tokenization OK Payment OK, Successful 3D Secure. 3DS form will be automatically completed.
- 4153013999700321	
- 11/2023	
- 321	

Tokenization OK Payment OK, 3D Secure attempt. 3DS will be automatically attempted.
- 4153013999700339	
- 11/2023	
- 339	

Tokenization (OK) Payment (OK), 3D Secure fails. The "cardholder_authentication" response parameter will be "no". It is at discretion of the merchant to accept or reject unauthentication transactions. If the merchant decides to decline the payment, the transaction should be reverted.
- 4153013999700347	
- 11/2023	
- 347

Tokenization OK Payment FAIL, Successful 3D Secure. 3DS form password "secret". Insufficient funds in the test bank account.
- 4153013999700354	
- 11/2023	
- 354	

Tokenization OK Payment OK, with 3DS, Soft decline when charging saved card using Customer Initiated Transaction (requires 3DS). 3DS form password "secret".
- 4153013999701162	
- 11/2023	
- 162	

Tokenization OK Payment OK, with 3DS, Soft decline when charging saved card using Customer Initiated Transaction (requires 3DS). 3DS form will be automatically completed.	
- 4153013999701170	
- 11/2023	
- 170	

Tokenization OK Payment OK, Non-EU - "one leg out" card, not enrolled to 3DS. The "cardholder_authentication" response parameter will be "attempted".	
- 4153013999700024	
- 11/2023	
- 024	

Tokenization OK Payment FAIL, Non-EU - "one leg out" card, not enrolled to 3DS. Insufficient funds in the test bank account.	
- 4153013999700156	
- 11/2023	
- 156

**Comment by tssge** [comment]
While the cards themselves seem to do as per their description, it seems that the 3DS for some reason doest not work correctly.

Completing 3DS with the cards requiring 3DS during CIT charge attempts ultimately redirects the user to the following type of URL:
```https://api.checkout.fi/token/payment/cit/charge/808e3d40-6a18-11ea-b3ce-83d32ae7d26c?sph-amount=12100&signature=SPH1+checkout_1+4fcd83ade25cef4c2595161db1e1c2d2935f75be66164d8040ff702da5754ce4&sph-account=checkout&sph-currency=EUR&sph-merchant=checkout&sph-transaction-id=e5fe2e5f-52d6-4776-9260-f065881aba8b&sph-order=1854753353&sph-timestamp=2020-03-19T19%3A34%3A12Z&sph-request-id=77557a95-e678-4695-9987-545fd57d6d42&sph-success=OK```

To which the Checkout server responds with 404 always, and I can't seem to figure out myself what's wrong with the URL

![image](https://user-images.githubusercontent.com/2301748/77108396-62f6df80-6a22-11ea-832b-292c1b02f9ec.png)

When a card tokenization is attempted and 3DS is performed it works fine. Only CIT charge and authorization-hold don't work.

The cards attempted were:

> Tokenization OK Payment OK, with 3DS, Soft decline when charging saved card using Customer Initiated Transaction (requires 3DS). 3DS form password "secret".
> 
> * 4153013999701162
> * 11/2023
> * 162
> 
> Tokenization OK Payment OK, with 3DS, Soft decline when charging saved card using Customer Initiated Transaction (requires 3DS). 3DS form will be automatically completed.
> 
> * 4153013999701170
> * 11/2023
> * 170

**Comment by Ahtoranta** [comment]
Thanks for pointing that out. I think I found a bug which causes that. We will fix that asap.

**Comment by Ahtoranta** [comment]
This will be fixed on next release planned for tomorrow (25.3).

**Comment by tssge** [comment]
Sorry to rush you @Ahtoranta, but any update on this one?

**Comment by tssge** [comment]
Closing, as this issue seems to be fixed
