### ISSUE TITLE
Tokenization with examples

### ISSUE THREAD

**Issue by odeporkka** [CheckoutFinland/psp-api#68]
Hi,

Adding tokenized cards documentation could use some improvements. I got it finally working with node, but it seems hmac signature is using ALL fields starting with checkout-, not just ones mentioned in authentication part. Also when using example hmac calculation, body part is empty which really isn't case when using forms (and content-type header is something else than json which is mentioned in authentication part, but it comes automatically when using forms). Some working examples would also be really nice. 

Here is React frontend form I used, feel free to use/modify it as example. Works easily with for example parent component  conditional rendering if requestObject is not undefined:

```
import React, { useEffect } from 'react';

/**
 * Hidden form which is automatically submitted.
 *
 * @param requestObject     Object containing form key-value pairs
 */
const AddCardForm = ({ requestObject }) => {
    useEffect(() => {
        document.forms.namedItem('addCardForm').submit();
    }, []);

    const checkoutAddCardUrl = 'https://api.checkout.fi/tokenization/addcard-form';

    return (
        <form method="post" action={checkoutAddCardUrl} id="addCardForm">
            {Object.keys(requestObject).map((key) => (
                <input type="hidden" name={key} key={key} value={requestObject[key]} />
                ))}
        </form>
    );
};

export default AddCardForm;

**Comment by tssge** [comment]
Duplicate / related https://github.com/CheckoutFinland/psp-api/issues/59

**Comment by Ahtoranta** [comment]
We have added dockerized php test shop which includes tokenization and token payments to test api calls. Hopefully soon at least typescript test shop as well. https://github.com/CheckoutFinland/php-test-webshop
