### ISSUE TITLE
instance.stamp already exists for merchant could have more meta data

### ISSUE THREAD

**Issue by thejhh** [CheckoutFinland/psp-api#79]
If this error message would provide the transaction ID in the meta data, it would be easier to recover from this.

```
{"status":"error","message":"Request payload validation failed.","meta":["instance.stamp or instance.item.stamp already exists for merchant."]}
```

In my case I had already created a transaction but my own code had failed to save it in the database, so I didn't have transaction ID mapped to my own stamp, and so could not fetch the transaction -- and my code tried to create a new one for the same invoice.

**Comment by thejhh** [comment]
Well, I guess I have understood something wrong, since the GET request for a transaction does not return everything -- so even if this would be true, I couldn't get payment information again, and would have to create a new transaction anyway.

**Comment by cibelius** [comment]
Hi thejhh, and thanks for reporting the issue!

Unfortunately the stamp has to be unique for each request to the [Payment Create API](https://checkoutfinland.github.io/psp-api/#/?id=create), as we create an open payment into our system for each successful request.

To avoid duplicate stamps, you can e.g. create a random uuid as the stamp for each request and bind it to your transaction in your database.

Let me know if something is still unclear!

We apologize for taking so long to reply, we have unfortunately been neglecting the GitHub issues for the past year or so. We intend to pay more attention to our GitHub repo in the future.
