### ISSUE TITLE
Success callback checkout-provider parameter gets nag value

### ISSUE THREAD

**Issue by samuliasmala** [CheckoutFinland/psp-api#84]
Success callback `checkout-provider` parameter gets `nag` value for S-Pankki, Danske Bank and Ålandbanken. There is nothing about this mentioned in the [callback API](https://checkoutfinland.github.io/psp-api/#/?id=redirect-and-callback-url-parameters) or [provider list](https://checkoutfinland.github.io/psp-api/#/payment-method-providers). What is that `nag` meaning and how to get the payment provider name in those cases?

**Comment by loueranta** [comment]
@samuliasmala Thanks for reporting, we will fix this asap!

`nag` is internal parameter used in the backend and it shouldn't be visible on the API callbacks.

**Comment by cibelius** [comment]
This should now be fixed, our backup payment polling system was sending an internal code `nag` instead of the bank name in `checkout-provider` query parameter.

Thanks for reporting the issue!
